"use client";

import React, { useState } from "react";
import Link from "next/link";
import { CaseReport as CaseReportType } from "@/lib/api";
import { DiffViewer } from "./DiffViewer";
import { VerificationPanel } from "./VerificationPanel";
import { EvidencePanel } from "./EvidencePanel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { CheckCircle2, XCircle, ArrowLeft, Code, FileText, Check, Sparkles, Download, AlertOctagon } from "lucide-react";

interface Props {
  report: CaseReportType;
}

export function CaseReport({ report }: Props) {
  const [showJson, setShowJson] = useState(false);
  const [copied, setCopied] = useState(false);
  const isReview = report.case_type === "repo_review";
  const isFailed = report.status === "failed";

  const handleCopyJson = () => {
    navigator.clipboard.writeText(JSON.stringify(report, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadReport = () => {
    const shortId = report.case_id.replace(/^case_/, "");
    const dateStr = new Date().toISOString().split("T")[0];

    const evidenceSection =
      report.key_evidence && report.key_evidence.length > 0
        ? report.key_evidence
            .map(
              (e, idx) =>
                `### ${idx + 1}. ${e.claim}\n- **File:** \`${e.file}${e.line ? `:${e.line}` : ""}\`\n- **Confidence:** ${Math.round(e.confidence * 100)}%\n- **Observation:** ${e.description}${e.code_snippet ? `\n\n\`\`\`\n${e.code_snippet}\n\`\`\`` : ""}`
            )
            .join("\n\n")
        : "_No specific findings recorded._";

    const testSection = report.verification
      ? `- **Command:** \`${report.verification.command}\`\n- **Exit Code:** ${report.verification.exit_code}\n- **Status:** ${report.verification.passed ? "PASSED (VERIFIED)" : report.verification.exit_code === 5 ? "NO TESTS FOUND (0 items collected)" : "FAILED"}\n\n\`\`\`\n${report.verification.stdout || report.verification.stderr || "No output"}\n\`\`\``
      : "_Automated test verification was not executed._";

    const patchSection = report.patch
      ? `### Unified Diff\n\`\`\`diff\n${report.patch.unified_diff}\n\`\`\`\n\n**Explanation:**\n${report.patch.explanation || "No explanation provided."}`
      : isReview
      ? "_No code modifications required._"
      : "_No patch generated._";

    const markdownContent = [
      `# Agent Holmes — ${isReview ? "Repository Audit Report" : "Bug Investigation Report"}`,
      ``,
      `**Dossier Reference:** #${shortId}  `,
      `**Target Repository:** \`${report.repo_url}\`  `,
      `**Date:** ${new Date().toUTCString()}  `,
      `**Type:** ${isReview ? "Code Review & Quality Audit" : "Targeted Bug Investigation"}  `,
      `**Verdict:** ${report.solved ? "PASSED / RESOLVED" : isFailed ? "FAILED / ERROR" : "ISSUES IDENTIFIED"}  `,
      ``,
      `---`,
      ``,
      `## 1. Executive Summary`,
      `${report.root_cause || report.summary}`,
      ``,
      `---`,
      ``,
      `## 2. Key Hypothesis & Recommendations`,
      report.winning_hypothesis
        ? `### ${report.winning_hypothesis.title} (${Math.round(report.winning_hypothesis.confidence * 100)}% Confidence)\n${report.winning_hypothesis.description}`
        : "_No hypotheses recorded._",
      ``,
      `---`,
      ``,
      `## 3. Findings & Evidence`,
      evidenceSection,
      ``,
      `---`,
      ``,
      `## 4. Test Verification Engine`,
      testSection,
      ``,
      `---`,
      ``,
      `## 5. Patch Synthesis`,
      patchSection,
      ``,
      `---`,
      `*Report autonomously generated by Agent Holmes Cyber Forensic Engine*`,
    ].join("\n");

    const blob = new Blob([markdownContent], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `AgentHolmes-${isReview ? "Audit" : "Investigation"}-${shortId}-${dateStr}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Prominent Resolution Banner */}
      <div
        className={`p-6 rounded-xl border flex flex-col md:flex-row items-start md:items-center justify-between gap-4 ${
          report.solved
            ? "bg-gradient-to-r from-emerald-950/80 via-emerald-900/40 to-slate-900 border-emerald-500/50 shadow-[0_0_30px_rgba(16,185,129,0.12)]"
            : "bg-gradient-to-r from-rose-950/80 via-rose-900/40 to-slate-900 border-rose-500/50 shadow-[0_0_30px_rgba(244,63,94,0.12)]"
        }`}
      >
        <div className="flex items-center gap-4">
          <div
            className={`w-12 h-12 rounded-full flex items-center justify-center shrink-0 ${
              report.solved
                ? "bg-emerald-500 text-slate-950"
                : "bg-rose-500 text-white"
            }`}
          >
            {report.solved ? (
              <CheckCircle2 className="w-7 h-7" />
            ) : isFailed ? (
              <AlertOctagon className="w-7 h-7" />
            ) : (
              <XCircle className="w-7 h-7" />
            )}
          </div>
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span
                className={`font-black text-xl tracking-wider ${
                  report.solved ? "text-emerald-400" : "text-rose-400"
                }`}
              >
                {report.solved
                  ? isReview
                    ? "AUDIT COMPLETE / HEALTHY"
                    : "CASE SOLVED"
                  : isFailed
                  ? isReview
                    ? "AUDIT HALTED / ERROR"
                    : "INVESTIGATION FAILED / ERROR"
                  : isReview
                  ? "AUDIT REPORT / ISSUES IDENTIFIED"
                  : "CASE FAILED / UNVERIFIED"}
              </span>
              <Badge variant="outline" className="text-xs border-slate-700 text-slate-400 font-mono">
                {isReview ? "REVIEW" : "BUG"} · #{report.case_id.replace(/^case_/, "")}
              </Badge>
            </div>
            <p className="text-sm text-slate-300 font-sans max-w-2xl leading-relaxed">
              {report.summary}
            </p>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2 self-stretch md:self-auto justify-end">
          <Button
            variant="outline"
            size="sm"
            onClick={handleDownloadReport}
            className="border-sky-500/40 bg-sky-950/40 hover:bg-sky-900/60 text-sky-200 hover:text-white font-mono text-xs flex items-center gap-1.5"
            title="Download executive audit report in Markdown (.md) format"
          >
            <Download className="w-3.5 h-3.5 text-sky-400" />
            Download Report
          </Button>

          <Button
            variant="outline"
            size="sm"
            onClick={() => setShowJson(!showJson)}
            className="border-slate-700 text-slate-300 hover:bg-slate-800 font-mono text-xs flex items-center gap-1.5"
          >
            <Code className="w-3.5 h-3.5" />
            {showJson ? "Hide JSON" : "Raw JSON"}
          </Button>

          <Link href="/">
            <Button
              size="sm"
              className={
                report.solved
                  ? "bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-semibold"
                  : "bg-slate-800 hover:bg-slate-700 text-slate-200"
              }
            >
              <ArrowLeft className="w-3.5 h-3.5 mr-1.5" />
              {isReview ? "New Audit" : "New Investigation"}
            </Button>
          </Link>
        </div>
      </div>

      {showJson && (
        <div className="p-4 rounded-lg bg-[#060a14] border border-slate-800 relative font-mono text-xs text-slate-300 overflow-x-auto">
          <div className="flex items-center gap-2 absolute top-3 right-3">
            <button
              onClick={handleCopyJson}
              className="text-xs bg-slate-800 hover:bg-slate-700 px-2.5 py-1 rounded text-slate-300 flex items-center gap-1 transition-colors"
            >
              {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <FileText className="w-3 h-3" />}
              {copied ? "Copied JSON" : "Copy JSON"}
            </button>
          </div>
          <pre>{JSON.stringify(report, null, 2)}</pre>
        </div>
      )}

      {/* Main Resolution Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left Column: Root Cause & Diff */}
        <div className="space-y-6">
          <Card className="bg-[#0c1220] border-slate-800 text-slate-100">
            <CardHeader className="py-3 px-4 border-b border-slate-800 bg-[#080d1a] flex flex-row items-center gap-2">
              <Sparkles className="w-4 h-4 text-emerald-400" />
              <CardTitle className="text-sm font-semibold tracking-wide">
                {isFailed
                  ? "FAILURE DIAGNOSTICS"
                  : isReview
                  ? "EXECUTIVE AUDIT SUMMARY"
                  : "IDENTIFIED ROOT CAUSE"}
              </CardTitle>
            </CardHeader>
            <CardContent className="p-4 space-y-3">
              <div
                className={`p-3.5 rounded-lg border text-xs leading-relaxed font-sans ${
                  isFailed
                    ? "bg-rose-950/20 border-rose-800/40 text-rose-200"
                    : "bg-emerald-950/20 border-emerald-800/40 text-emerald-200"
                }`}
              >
                <span
                  className={`font-bold block mb-1 ${
                    isFailed ? "text-rose-300" : "text-emerald-300"
                  }`}
                >
                  {isFailed
                    ? "Failure Details:"
                    : isReview
                    ? "Audit Assessment:"
                    : "Root Cause Diagnosis:"}
                </span>
                {report.root_cause || report.summary}
              </div>

              {report.winning_hypothesis && (
                <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-xs">
                  <div className="flex items-center justify-between mb-1">
                    <span className="font-semibold text-slate-200">
                      {isReview ? "Key Recommendation" : "Confirmed Hypothesis"}
                    </span>
                    <Badge className="bg-emerald-500/20 text-emerald-400 border-emerald-500/30 text-[10px]">
                      {Math.round(report.winning_hypothesis.confidence * 100)}% CONFIDENCE
                    </Badge>
                  </div>
                  <p className="text-slate-400 font-sans leading-relaxed">
                    {report.winning_hypothesis.description}
                  </p>
                </div>
              )}
            </CardContent>
          </Card>

          {report.patch ? (
            <DiffViewer
              unifiedDiff={report.patch.unified_diff}
              explanation={report.patch.explanation}
              filePaths={report.patch.file_paths}
            />
          ) : (
            <div className="p-6 rounded-lg border border-slate-800 bg-slate-900/40 text-center text-xs text-slate-500">
              {isFailed
                ? "Investigation was halted due to an execution error before patch synthesis or audit could complete."
                : isReview
                ? "No code changes required — repository passed architectural audit."
                : "No patch was generated for this case."}
            </div>
          )}
        </div>

        {/* Right Column: Verification & Evidence */}
        <div className="space-y-6">
          <VerificationPanel results={report.verification ? [report.verification] : []} />
          <EvidencePanel evidence={report.key_evidence} />
        </div>
      </div>
    </div>
  );
}
